# Generated by Django 4.0.3 on 2022-03-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mango',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
